### PR TITLE
Disable web server by default and make it enabled by attribute

### LINKED ISSUE #609: [monit] allow the disabling of the monit web server
The monit web server serves little purpose unless it's specifically used in an environment. We believe that it should be disabled by default and have an attribute which allows the user to enable it if they choose to do so.

Leaving it enabled by default simply increases the attack surface for someone looking to cause trouble.

Resolved by https://github.com/rcbops-cookbooks/monit/pull/29

### PR DESCRIPTION
**Pull request by odyssey4me**
Resolves https://github.com/rcbops/chef-cookbooks/issues/609

### CODE REVIEW

**Comment by odyssey4me** [comment]
retest

**Comment by odyssey4me** [comment]
It looks like jenkins needs a massage. ;)

**Comment by odyssey4me** [comment]
retest

**Comment by willkelly** [comment]
retest

**Pull request closed without merging**
